/**
 * The art ledgers: which beasts are still waiting on their drawings, and who drew the ones
 * we borrowed.
 *
 * Two documents are generated from this module and checked against it, the same way the
 * card catalog is: `CREDITS.md` from `CREATURE_ART`, and `docs/sprite-requests.md` from
 * `COMPANION_ART_PENDING`. Both are written by `npm run art:credits` / `npm run art:requests`,
 * and a test fails the moment either file disagrees with the data — a credit that drifted
 * out of date is a licence quietly broken, and a request list that drifted is a beast
 * nobody knows to paint.
 */

import { companionById, type CompanionDef } from './companions.js';
import { CARDS } from './cards/index.js';
import { CREATURE_ART, LICENCES, type CreatureArt } from './art.js';

/**
 * What a generated placeholder sprite says about itself, in a PNG `tEXt` chunk.
 *
 * The mark is how the suite tells a stand-in from a painting without a list of hashes: every
 * file the placeholder script writes carries it, and nothing an artist exports ever will.
 */
export const PLACEHOLDER_MARK = 'conjure-placeholder';

/**
 * Species whose three sprites on disk are generated stand-ins rather than their own art.
 *
 * A two-way ledger. A species listed here must have placeholder files carrying
 * `PLACEHOLDER_MARK`; a species not listed must have real ones. So painting a beast is two
 * changes that have to arrive together — the files, and the line struck off here — and
 * forgetting either fails the suite rather than shipping a silhouette nobody knows about.
 *
 * Every species must have *some* file on disk regardless. The district drops the follower
 * when its front sprite is missing, so a stand-in is the difference between a new beast
 * walking beside the player as a shape and not walking beside them at all.
 */
export const COMPANION_ART_PENDING: readonly string[] = [
  // The third bloodlines of Pyre, Frost and Surge.
  'phoenix',
  'badger',
  'mammoth',
  'ermine',
  'eel',
  'pangolin',
];

/** The file stem a species' sprites are saved under. */
export function spriteStemOf(species: CompanionDef): string {
  return species.artId ?? species.id;
}

// ------------------------------------------------------------------ CREDITS.md

const CREDITS_PREAMBLE = `# Credits

This file is generated by \`npm run art:credits\` from \`src/core/data/art.ts\`. Edit that
file, not this one; the test suite fails when the two disagree.

## The game's own art

The Commander, the Companion sprites under \`public/assets/sprites/companions/\` and the
townsfolk sheets under \`public/assets/sprites/\` are CONJURE's own work.

## Third-party art

Bundled drawings keep their authors' licences, listed below with the cards that wear them.
Only CC0 and attribution-only licences are accepted into this game: no share-alike, GPL,
NonCommercial or NoDerivatives work is bundled.
`;

/** `CREDITS.md`, exactly as it should read for this registry. */
export function creditsMarkdown(registry: Readonly<Record<string, CreatureArt>> = CREATURE_ART): string {
  const works = new Map<string, { art: CreatureArt; cards: string[] }>();
  for (const [cardId, art] of Object.entries(registry)) {
    const key = `${art.title}\u0000${art.author}\u0000${art.source}\u0000${art.licence}`;
    const entry = works.get(key) ?? { art, cards: [] };
    entry.cards.push(cardId);
    works.set(key, entry);
  }

  const lines = [CREDITS_PREAMBLE];
  if (works.size === 0) {
    lines.push('None yet. Every creature on the board is drawn procedurally.\n');
    return lines.join('\n');
  }

  const sorted = [...works.values()].sort(
    (a, b) => a.art.author.localeCompare(b.art.author) || a.art.title.localeCompare(b.art.title),
  );
  for (const { art, cards } of sorted) {
    const licence = LICENCES[art.licence];
    const names = cards
      .sort()
      .map((id) => CARDS[id]?.name ?? id)
      .join(', ');
    lines.push(`### ${art.title}`);
    lines.push('');
    lines.push(`- **Author:** ${art.author}`);
    lines.push(`- **Source:** ${art.source}`);
    lines.push(`- **Licence:** [${licence.name}](${licence.url})`);
    lines.push(`- **Used for:** ${names}`);
    lines.push('');
  }
  return lines.join('\n');
}

// ------------------------------------------------------------ sprite requests

/** `docs/sprite-requests.md`, exactly as it should read for this ledger. */
export function spriteRequestsMarkdown(pending: readonly string[] = COMPANION_ART_PENDING): string {
  const lines = [
    '# Sprite requests',
    '',
    'Generated by `npm run art:requests` from `COMPANION_ART_PENDING` in',
    '`src/core/data/artLedger.ts`. Every species below is running on a generated',
    'silhouette until its own art arrives.',
    '',
    '## What each species needs',
    '',
    '- Three PNGs, `front`, `back` and `side`, in `public/assets/sprites/companions/`.',
    '- Painted, anti-aliased, on a transparent background, about 150–330 px tall, matching',
    '  the existing beasts: the feet on the bottom edge, and no ground shadow baked in.',
    '- `side` faces left, and is a true profile: the game mirrors it for the other bearing.',
    '- When the files are in, strike the species off `COMPANION_ART_PENDING` and rerun',
    '  `npm run art:requests`. The suite checks both halves.',
    '',
  ];

  if (pending.length === 0) {
    lines.push('Nothing is waiting. Every species has its own art.', '');
    return lines.join('\n');
  }

  lines.push('## Waiting', '');
  for (const id of pending) {
    const species = companionById(id);
    if (!species) {
      lines.push(`### ${id}`, '', '- **Unknown species.** Remove it from the ledger.', '');
      continue;
    }
    const body = CARDS[species.unitCardId]?.unit;
    const stem = spriteStemOf(species);
    lines.push(`### ${species.name}, ${species.title}`);
    lines.push('');
    lines.push(`- **Schools:** ${species.grimoire.schools.join(' + ')}`);
    if (body) {
      lines.push(
        `- **Body:** ${body.archetype}${body.footprint > 1 ? ', a 2x2 behemoth' : ''}` +
          `, moves ${body.mov}, reaches ${body.rangeMax}`,
      );
    }
    lines.push(`- **Brief:** ${species.blurb}`);
    lines.push(`- **Files:** \`${stem}-front.png\`, \`${stem}-back.png\`, \`${stem}-side.png\``);
    lines.push('');
  }
  return lines.join('\n');
}

