/**
 * GENERATED by `npm run folk:measure`. Do not edit.
 *
 * Where each townsperson actually is inside their sheet, in sheet pixels, measured off
 * the alpha channel at the same threshold the material cuts at. See
 * `scripts/measure-folk-sheets.ts` for why these are measured rather than divided, and
 * `src/render/folk.ts` for what is hung off them.
 */

export interface FolkBox {
  readonly sheet: string;
  readonly x: number;
  readonly y: number;
  readonly w: number;
  readonly h: number;
}

export const FOLK_BOXES = {
  // Elder_Blacksmith_HealerPrincess_Shopkeeper_FarmerWife_FarmerDaughter_FemaleMercenary_ScribeScholar_MinerA_MinerB_Bard_TownGuard.png
  elder: { sheet: 'painted', x: 16, y: 29, w: 84, h: 154 },
  blacksmith: { sheet: 'painted', x: 121, y: 22, w: 95, h: 161 },
  healer: { sheet: 'painted', x: 227, y: 28, w: 82, h: 154 },
  shopkeeper: { sheet: 'painted', x: 16, y: 218, w: 87, h: 148 },
  farmer_wife: { sheet: 'painted', x: 137, y: 213, w: 79, h: 153 },
  farmer_daughter: { sheet: 'painted', x: 240, y: 213, w: 77, h: 153 },
  mercenary: { sheet: 'painted', x: 28, y: 388, w: 78, h: 162 },
  scribe_scholar: { sheet: 'painted', x: 120, y: 398, w: 84, h: 153 },
  miner_a: { sheet: 'painted', x: 220, y: 398, w: 90, h: 151 },
  miner_b: { sheet: 'painted', x: 17, y: 589, w: 88, h: 148 },
  bard: { sheet: 'painted', x: 129, y: 587, w: 82, h: 151 },
  town_guard: { sheet: 'painted', x: 211, y: 573, w: 94, h: 164 },
  // Blacksmith_Weaver_Potter_Glassblower_Innkeeper_Baker_Grocer_Scribe_TownCrier_Herbalist_BardB_NightWatchman.png
  blacksmith_px: { sheet: 'trades', x: 47, y: 112, w: 411, h: 655 },
  weaver: { sheet: 'trades', x: 458, y: 184, w: 423, h: 582 },
  potter: { sheet: 'trades', x: 923, y: 139, w: 387, h: 615 },
  glassblower: { sheet: 'trades', x: 29, y: 910, w: 365, h: 602 },
  innkeeper: { sheet: 'trades', x: 448, y: 907, w: 414, h: 603 },
  baker: { sheet: 'trades', x: 893, y: 924, w: 424, h: 593 },
  grocer: { sheet: 'trades', x: 34, y: 1660, w: 424, h: 625 },
  scribe: { sheet: 'trades', x: 484, y: 1682, w: 391, h: 600 },
  town_crier: { sheet: 'trades', x: 907, y: 1682, w: 394, h: 606 },
  herbalist: { sheet: 'trades', x: 55, y: 2417, w: 372, h: 597 },
  bard_b: { sheet: 'trades', x: 547, y: 2421, w: 323, h: 597 },
  night_watchman: { sheet: 'trades', x: 899, y: 2389, w: 380, h: 627 },
  // Butcher_Seamstress_Carpenter_Fisherman_Brewer_Cobbler_Alchemist_Apothecary_Jeweler_Cartographer_ChildBeggar_Noblewoman.png
  butcher: { sheet: 'crafts', x: 46, y: 114, w: 417, h: 639 },
  seamstress: { sheet: 'crafts', x: 522, y: 143, w: 313, h: 606 },
  carpenter: { sheet: 'crafts', x: 903, y: 115, w: 374, h: 636 },
  fisherman: { sheet: 'crafts', x: 38, y: 853, w: 425, h: 657 },
  brewer: { sheet: 'crafts', x: 492, y: 898, w: 395, h: 612 },
  cobbler: { sheet: 'crafts', x: 924, y: 915, w: 378, h: 599 },
  alchemist: { sheet: 'crafts', x: 65, y: 1636, w: 357, h: 644 },
  apothecary: { sheet: 'crafts', x: 487, y: 1655, w: 384, h: 623 },
  jeweler: { sheet: 'crafts', x: 933, y: 1650, w: 323, h: 630 },
  cartographer: { sheet: 'crafts', x: 58, y: 2400, w: 353, h: 604 },
  child_beggar: { sheet: 'crafts', x: 503, y: 2455, w: 299, h: 544 },
  noblewoman: { sheet: 'crafts', x: 883, y: 2392, w: 425, h: 613 },
  // ButcherB_BrewerB_Fishmonger_Taylor_CobblerB_Town GuardB_Miller_Harold_CartographerB_Tax Collector_Tanner_Street Urchin.png
  butcher_b: { sheet: 'alts', x: 29, y: 114, w: 418, h: 646 },
  brewer_b: { sheet: 'alts', x: 447, y: 138, w: 446, h: 630 },
  fishmonger: { sheet: 'alts', x: 913, y: 122, w: 419, h: 643 },
  taylor: { sheet: 'alts', x: 24, y: 934, w: 416, h: 605 },
  cobbler_b: { sheet: 'alts', x: 473, y: 941, w: 441, h: 603 },
  town_guard_b: { sheet: 'alts', x: 914, y: 934, w: 388, h: 603 },
  miller: { sheet: 'alts', x: 29, y: 1691, w: 460, h: 623 },
  herald: { sheet: 'alts', x: 489, y: 1705, w: 374, h: 607 },
  cartographer_b: { sheet: 'alts', x: 886, y: 1712, w: 443, h: 600 },
  tax_collector: { sheet: 'alts', x: 30, y: 2434, w: 405, h: 580 },
  tanner: { sheet: 'alts', x: 464, y: 2411, w: 439, h: 599 },
  street_urchin: { sheet: 'alts', x: 973, y: 2477, w: 329, h: 532 },
} as const satisfies Record<string, FolkBox>;
